"""
GraySentinel Project 02: Project 01 Recon JSON Ingestion and Attack Surface Parser.
Ingests authorized web reconnaissance artifacts, checks schema compliance,
and correlates observations into structured candidate security findings.
"""

import json
import os
from typing import Dict, Any, List, Tuple
from .models import (
    ReconData,
    ReconService,
    ReconEndpoint,
    Finding,
    EvidenceItem,
    Remediation,
    Severity,
    Confidence,
    ValidationStatus,
)
from .errors import ReconParseError


REQUIRED_RECON_KEYS = {"target", "scan_id", "timestamp", "open_ports", "endpoints"}


def validate_recon_schema(data: Dict[str, Any]) -> None:
    """Verifies that the imported JSON conforms to the Project 01 Recon schema."""
    if not isinstance(data, dict):
        raise ReconParseError(
            message="Reconnaissance data payload must be a valid JSON object.",
            reason="Root entity is not a dictionary.",
            suggested_action="Verify that the Project 01 output export is a valid JSON file."
        )

    missing = REQUIRED_RECON_KEYS - set(data.keys())
    if missing:
        raise ReconParseError(
            message=f"Reconnaissance JSON missing required keys: {', '.join(sorted(missing))}",
            reason=f"The provided file does not match Project 01 schema specification.",
            suggested_action="Ensure the file was generated by GraySentinel Project 01 or load the sanitized sample dataset."
        )


def load_recon_json(filepath: str) -> ReconData:
    """Loads and deserializes Project 01 Reconnaissance JSON data from disk."""
    if not os.path.exists(filepath):
        raise ReconParseError(
            message=f"Target recon file not found: '{filepath}'",
            reason=f"Path does not exist on filesystem.",
            suggested_action="Verify path or run in Demo Mode using the bundled sanitized dataset."
        )

    try:
        with open(filepath, "r", encoding="utf-8") as f:
            raw_data = json.load(f)
    except json.JSONDecodeError as exc:
        raise ReconParseError(
            message=f"Malformed JSON in '{filepath}'",
            reason=f"Syntax error on line {exc.lineno}: {exc.msg}",
            suggested_action="Inspect the file for JSON syntax errors or re-export from Project 01."
        )
    except Exception as exc:
        raise ReconParseError(
            message=f"Failed to read recon file '{filepath}'",
            reason=str(exc),
            suggested_action="Check file read permissions and disk status."
        )

    validate_recon_schema(raw_data)

    services = [
        ReconService(
            port=int(p.get("port", 0)),
            protocol=p.get("protocol", "tcp"),
            service=p.get("service", "unknown"),
            state=p.get("state", "open"),
            banner=p.get("banner", ""),
        )
        for p in raw_data.get("open_ports", [])
    ]

    endpoints = [
        ReconEndpoint(
            path=ep.get("path", "/"),
            status_code=int(ep.get("status_code", 200)),
            method=ep.get("method", "GET"),
            content_type=ep.get("content_type", "text/html"),
            response_size=int(ep.get("response_size", 0)),
            title=ep.get("title", ""),
            parameters=ep.get("parameters", []),
        )
        for ep in raw_data.get("endpoints", [])
    ]

    return ReconData(
        target=raw_data["target"],
        scan_id=raw_data["scan_id"],
        timestamp=raw_data["timestamp"],
        scan_type=raw_data.get("scan_type", "Authorized Web Reconnaissance"),
        is_demo=bool(raw_data.get("is_demo", True)),
        open_ports=services,
        endpoints=endpoints,
        missing_security_headers=raw_data.get("missing_security_headers", []),
        metadata=raw_data.get("metadata", {}),
    )


def generate_candidate_findings(recon: ReconData) -> List[Finding]:
    """
    Analyzes reconnaissance observations to generate structured candidate security findings.
    Correlates open ports, exposed sensitive endpoints, and absent security headers.
    """
    candidates: List[Finding] = []
    finding_counter = 1

    # 1. Correlate Missing Defensive Security Headers
    if recon.missing_security_headers:
        fid = f"GS-SEC-{finding_counter:03d}"
        missing_str = ", ".join(recon.missing_security_headers)
        f = Finding(
            id=fid,
            title="Absence of Baseline Defensive HTTP Security Headers",
            description=(
                f"Web service at {recon.target} lacks modern protective HTTP response headers "
                f"({missing_str}). This degrades browser defense-in-depth protections against "
                "clickjacking, MIME-sniffing, and cross-site scripting."
            ),
            severity=Severity.LOW,
            confidence=Confidence.HIGH,
            affected_asset=f"https://{recon.target}/",
            source="PROJECT_01_RECON",
            validation_status=ValidationStatus.VALIDATED,
            cwe_id="CWE-693",
            cwe_name="Protection Mechanism Failure",
            owasp_category="A05:2021-Security Misconfiguration",
            cvss_score=3.7,
            cvss_vector="CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
            reproduction_steps=[
                f"Send an HTTP GET request to https://{recon.target}/",
                "Inspect response headers using curl or an intercepting proxy.",
                f"Verify the absence of headers: {missing_str}.",
            ],
            evidence=[
                EvidenceItem(
                    id=f"EVD-{finding_counter:03d}-01",
                    source=f"HTTP Header Audit on {recon.target}",
                    observation=f"Response headers lack defensive directives: {missing_str}",
                    relevant_data=f"Target: {recon.target}\nMissing: {missing_str}",
                    timestamp=recon.timestamp,
                    is_demo_sample=recon.is_demo,
                    verified=True,
                    notes="Verified through Project 01 header inspection module.",
                )
            ],
            remediation=Remediation(
                tactical=(
                    "Configure edge reverse proxy (Nginx, Caddy, or Cloudflare) to attach: "
                    "Content-Security-Policy, Strict-Transport-Security, X-Frame-Options, and X-Content-Type-Options."
                ),
                strategic=(
                    "Enforce centralized baseline header configurations in CI/CD container templates "
                    "and conduct automated weekly header regression checks."
                ),
                code_example=(
                    "# Nginx security header baseline\n"
                    "add_header Content-Security-Policy \"default-src 'self';\" always;\n"
                    "add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;\n"
                    "add_header X-Frame-Options \"DENY\" always;\n"
                    "add_header X-Content-Type-Options \"nosniff\" always;"
                ),
                references=[
                    "https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html",
                    "https://cwe.mitre.org/data/definitions/693.html",
                ],
            ),
            references=["https://owasp.org/Top10/A05_2021-Security_Misconfiguration/"],
            tags=["headers", "misconfiguration", "hardening"],
        )
        candidates.append(f)
        finding_counter += 1

    # 2. Correlate Exposed Sensitive Endpoints (e.g. .env, /admin, debug routes)
    for ep in recon.endpoints:
        path_lower = ep.path.lower()
        if ep.status_code in (200, 301, 302, 403):
            # Check for exposed config or backup files
            if any(term in path_lower for term in [".env", ".git", "config.json", "backup", "dump.sql"]):
                fid = f"GS-SEC-{finding_counter:03d}"
                f = Finding(
                    id=fid,
                    title=f"Publicly Accessible Configuration Artifact ({ep.path})",
                    description=(
                        f"The server exposes sensitive application configuration artifact at {ep.path} "
                        f"(HTTP Status {ep.status_code}). If unauthenticated visitors access this resource, "
                        "operational secrets, API keys, and database credentials could be compromised."
                    ),
                    severity=Severity.CRITICAL if ep.status_code == 200 else Severity.HIGH,
                    confidence=Confidence.HIGH,
                    affected_asset=f"https://{recon.target}{ep.path}",
                    source="PROJECT_01_RECON",
                    validation_status=ValidationStatus.VALIDATED,
                    cwe_id="CWE-200",
                    cwe_name="Exposure of Sensitive Information to an Unauthorized Actor",
                    owasp_category="A01:2021-Broken Access Control",
                    cvss_score=8.6 if ep.status_code == 200 else 7.1,
                    cvss_vector="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N",
                    reproduction_steps=[
                        f"Send unauthenticated GET request to https://{recon.target}{ep.path}",
                        f"Observe HTTP status code {ep.status_code} returned by web server.",
                        "Confirm sensitive environment variable keys or credentials in response payload.",
                    ],
                    evidence=[
                        EvidenceItem(
                            id=f"EVD-{finding_counter:03d}-01",
                            source="HTTP Endpoint Enumeration",
                            observation=f"Accessible endpoint returned HTTP {ep.status_code} with size {ep.response_size} bytes",
                            relevant_data=f"GET {ep.path} HTTP/1.1 -> {ep.status_code} OK (Content-Type: {ep.content_type})",
                            timestamp=recon.timestamp,
                            is_demo_sample=recon.is_demo,
                            verified=True,
                            notes="Flagged as sensitive path pattern.",
                        )
                    ],
                    remediation=Remediation(
                        tactical=f"Immediately block external access to {ep.path} and rotate any exposed credentials.",
                        strategic="Audit build pipelines to exclude dot-files and backup archives from web document roots.",
                        code_example="location ~ /\\.(?!well-known).* { deny all; return 404; }",
                    ),
                    references=["https://cwe.mitre.org/data/definitions/200.html"],
                    tags=["exposure", "sensitive-data", "configuration"],
                )
                candidates.append(f)
                finding_counter += 1

            # Check for exposed administration portals or internal metrics
            elif any(term in path_lower for term in ["/admin", "/actuator", "/metrics", "/debug", "/console"]):
                fid = f"GS-SEC-{finding_counter:03d}"
                f = Finding(
                    id=fid,
                    title=f"Unrestricted Access to Internal Interface ({ep.path})",
                    description=(
                        f"Administrative or monitoring endpoint discovered at {ep.path} returning HTTP {ep.status_code}. "
                        "Exposing internal portals increases the attack surface for credential stuffing, "
                        "brute-force attacks, and reconnaissance."
                    ),
                    severity=Severity.HIGH if ep.status_code == 200 else Severity.MEDIUM,
                    confidence=Confidence.HIGH,
                    affected_asset=f"https://{recon.target}{ep.path}",
                    source="PROJECT_01_RECON",
                    validation_status=ValidationStatus.REVIEW,
                    cwe_id="CWE-284",
                    cwe_name="Improper Access Control",
                    owasp_category="A01:2021-Broken Access Control",
                    cvss_score=7.3 if ep.status_code == 200 else 5.3,
                    cvss_vector="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
                    reproduction_steps=[
                        f"Issue GET request to https://{recon.target}{ep.path}",
                        f"Verify that endpoint responds with status {ep.status_code} without requiring network isolation.",
                    ],
                    evidence=[
                        EvidenceItem(
                            id=f"EVD-{finding_counter:03d}-01",
                            source="Recon Web Spidering",
                            observation=f"Route {ep.path} returned HTTP {ep.status_code}",
                            relevant_data=f"GET {ep.path} -> HTTP {ep.status_code} ({ep.title or 'No Title'})",
                            timestamp=recon.timestamp,
                            is_demo_sample=recon.is_demo,
                            verified=True,
                            notes="Administrative surface exposed.",
                        )
                    ],
                    remediation=Remediation(
                        tactical=f"Restrict access to {ep.path} using IP whitelisting or VPN gateway authentication.",
                        strategic="Enforce Zero Trust architecture principles for all internal administrative planes.",
                    ),
                    tags=["admin", "access-control", "attack-surface"],
                )
                candidates.append(f)
                finding_counter += 1

    # 3. Correlate Open Non-Standard Management / Database Ports
    for port in recon.open_ports:
        if port.port in (22, 3306, 5432, 6379, 27017, 8080, 9200):
            fid = f"GS-SEC-{finding_counter:03d}"
            f = Finding(
                id=fid,
                title=f"Direct Exposure of Management/Database Port ({port.port}/{port.protocol})",
                description=(
                    f"Port {port.port} ({port.service}) is reachable directly over the public/perimeter network. "
                    f"Service banner: '{port.banner or 'No banner'}'. Direct exposure allows remote adversaries "
                    "to conduct uninhibited brute-force attacks or exploit protocol-level vulnerabilities."
                ),
                severity=Severity.HIGH if port.port in (3306, 5432, 6379, 27017) else Severity.MEDIUM,
                confidence=Confidence.HIGH,
                affected_asset=f"{recon.target}:{port.port}",
                source="PROJECT_01_RECON",
                validation_status=ValidationStatus.VALIDATED,
                cwe_id="CWE-1188",
                cwe_name="Insecure Default Initialization of Resource",
                owasp_category="A05:2021-Security Misconfiguration",
                cvss_score=7.5 if port.port in (3306, 5432, 6379) else 5.3,
                cvss_vector="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                reproduction_steps=[
                    f"Execute TCP probe against {recon.target} on port {port.port}",
                    f"Confirm open state ({port.state}) and service identification ({port.service}).",
                ],
                evidence=[
                    EvidenceItem(
                        id=f"EVD-{finding_counter:03d}-01",
                        source="Network Port Sweep",
                        observation=f"Port {port.port}/{port.protocol} open. Service identified: {port.service}",
                        relevant_data=f"{recon.target}:{port.port} OPEN ({port.banner})",
                        timestamp=recon.timestamp,
                        is_demo_sample=recon.is_demo,
                        verified=True,
                        notes="Identified during perimeter reconnaissance sweep.",
                    )
                ],
                remediation=Remediation(
                    tactical=f"Apply firewall ingress rules (Security Group / iptables) to restrict port {port.port}.",
                    strategic="Migrate administrative access behind dedicated bastion hosts or Zero Trust access proxies.",
                ),
                tags=["network", "ports", "perimeter"],
            )
            candidates.append(f)
            finding_counter += 1

    return candidates
